modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="coalsword"
version="1.0.0"
displayName="Coal sword"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="alave, MCreator"

[[dependencies.coalsword]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



